##### ©2023 ATLAS CORPORATION // CREATE // ISSUE REPORT TEMPLATE BY SUPERPROINFINITY // ALL RIGHT RESERVED #####

name: Issue Report
description: File a Bug or Fatal issues
title: "[Issue]: "
labels: ["Bug", "triage" ]
assignees:
  - ROBLOX-ATLAS-GAMES
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
      
      Before reporting, please make sure that there isn't a similar opened issue.
      And please check out FAQ to find a solution. If not possible, you may file a Issue Report.
      
      Do not contains any Swearing Words unless this's a bug reproduce steps, and keep your inputs neat.
      We reserve the rights to ignore your issues without fixing.
- type: textarea
  id: bug-description
  attributes:
    label: Bug Description
    description: Explain what kind of bug did you encounter, and detailed information.
  validations:
    required: true
- type: textarea
  id: reproduce-steps
  attributes:
    label: Reproduce Steps
    description: How did you trigger this bug? Please explain it step by step in Ordered List or atleast a Video proof, and provide the expected behaviour.
  validations:
    required: true
- type: textarea
  id: error-logs
  attributes:
    label: Error Logs
    description: Please copy and paste the error logs that caused the issues.
    render: shell
- type: input
  attributes:
    label: Error Log ID
    description: Provide a Error Log ID given after the Error Message if possible.
    placeholder: "ABCD-EF12-3456-7890 (HEX-HEX-HEX-CODE)"
  validations:
    required: false
- type: input
  attributes:
    label: Modules
    description: What kind of Create Modules caused the issues?
    placeholder: "CreateClient / CreateServerSoftware / CreateAPI / Others"
  validations:
    required: true
- type: input
  attributes:
    label: Module Versions
    description: What version of Create Modules that you selected are using? **(<Latest> is not a version!)**
    placeholder: "e.g. CreateClient DEMO 1.0.0, CreateServerSoftware DEMO 1.0.0, CreateAPI DEMO 1.0.0"
  validations:
    required: true
- type: input
  attributes:
    label: World Location
    description: Provide the World Location if you selected CreateClient or CreateAPI.
    placeholder: "0.0.0.0/0000 (LOCATION/PORT)"
  validations:
    required: false
- type: input
  attributes:
    label: Additional Notes
    description: Provide a Additional Notes if necessary
  validations:
    required: false
- type: checkboxes
  id: terms-agrement
  attributes:
    label: Term Agreements
    description: By submitting this issue, you agree to follow our [Create ToS](https://atlas-corporations.gitbook.io/create/tos), [CreateAPI](https://atlas-corporations.gitbook.io/create-api/tou) ToS and this Form Rules.
    options:
      - label: "I agree to follow Create ToS and CreateAPI ToS and this Form Rules."
        required: true
      - label: "I have searched and ensured that there is isn't an similar opened issue regarding this"
        required: true
      - label: "I have searched and ensured that there isn't a possible solution from FAQ"
        required: true
      - label: "I was using or running the latest version (DEMO 1.0)"
        required: true

##### ©2023 ATLAS CORPORATION // CREATE // ISSUE REPORT TEMPLATE BY SUPERPROINFINITY // ALL RIGHT RESERVED #####
